baseurl = "http://customers.brepi.xyz/hans-koning/"
enableRobotsTXT = false
googleAnalytics = ""
languageCode = "en-us"
paginate = 10.0
theme = "hans-theme"
title = "Hans Koning website"

[languages]

  [languages.en]
  copyright = ""
  keywords = ""
  menuMore = "Show more"
  readMore = "Read more"
  readOtherPosts = "Read other posts"
  subtitle = "Uw decorateschilder"
  title = "Hans Koning"

    [languages.en.menu]

      [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"

      [[languages.en.menu.main]]
      identifier = "showcase"
      name = "Showcase"
      url = "/showcase"

    [languages.en.params]

      [languages.en.params.logo]
      logoHomeLink = "/"
      logoText = "HANS KONING - Decoratieschilder"

[params]
centerTheme = true
contentTypeName =  "item"
fullWidthTheme = true
showMenuItems = 2.0

[taxonomies]
category = "technieken"
